export default {
  login: 'Shivu150199',
  id: 105829038,
  node_id: 'U_kgDOBk7Srg',
  avatar_url: 'https://avatars.githubusercontent.com/u/105829038?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Shivu150199',
  html_url: 'https://github.com/Shivu150199',
  followers_url: 'https://api.github.com/users/Shivu150199/followers',
  following_url:
    'https://api.github.com/users/Shivu150199/following{/other_user}',
  gists_url: 'https://api.github.com/users/Shivu150199/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/Shivu150199/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Shivu150199/subscriptions',
  organizations_url: 'https://api.github.com/users/Shivu150199/orgs',
  repos_url: 'https://api.github.com/users/Shivu150199/repos',
  events_url: 'https://api.github.com/users/Shivu150199/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Shivu150199/received_events',
  type: 'User',
  site_admin: false,
  name: 'Shivam Singh gautam',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: true,
  bio: 'web developer',
  twitter_username: null,
  public_repos: 43,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2022-05-19T00:23:18Z',
  updated_at: '2023-05-16T22:53:12Z',
}
